app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', 'HomeController@index');
Route::resource('admin','NewsController');
Route::get('admin/{admin}/destroy',[
  'uses'=>'NewsController@destroy',
  'as' => 'admin.destroy'
]);
Route::resource('login','LoginController');
Route::get('logout','LoginController@logout');
Route::resource('register','AdministratorController');
Route::resource('news','AjaxReadController');
Route::get('news/{news}/destroy',[
  'uses'=>'AjaxReadController@destroy',
  'as' => 'news.destroy'
]);
Route::get('newsList','AjaxReadController@ajaxList');

Route::get('push','HomeController@ajaxList');

resources/views/admin/create.blade.php
@extends('layouts.principal-admin')
@section('content')
{!!Form::open(['route'=>'admin.store', 'method'=>'POST','files' => true])!!}
{!!Form::hidden('administrators_id', Auth::user()->id)!!}
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-filled">
            <div class="panel-heading">
                <h1 class="page-header">Register new news data</h1>
                Enter information below
            </div>
            <div class="panel-body">
               @include('admin.form.form')
            </div>
        </div>
    </div>
    <div class="col-md-6">
       {!!Form::submit('Register',['class'=>'btn btn-w-md btn-primary'])!!} <a class="btn btn-w-md btn-danger" href="{!! URL::to('admin') !!}">Cancel</a>
    </div>
</div>
{!! Form::close() !!}
@endsection

resources/views/admin/edit.blade.php
@extends('layouts.principal-admin')
@section('content')
{!!Form::model($new,['route'=>['admin.update',$new->id],'method'=>'PUT','files' => true])!!}
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-filled">
            <div class="panel-heading">
                <h1 class="page-header">Update new data</h1>
                Enter information below
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-6">
                        {!!Form::hidden('administrators_id', Auth::user()->id)!!}
                        {!!Form::label('title','Title: ')!!}
                        {!!Form::text('title',null,['id'=>'newsTitle','class'=>'form-control','required','min'=>10]) !!}<br>
                        {!!Form::label('text','Text: ')!!}
                        {!!Form::textarea('text',null,['id'=>'newsText','class'=>'form-control', 'rows' => 10,'min'=>20,'required']) !!}<br>
                        {!!Form::label('picturepath','Image:')!!}
                        {!!Form::file('picturepath',['class'=>'filestyle', 'data-input'=>'false','enctype'=>'multipart/form-data'])!!}<br>
                    </div>
                    <div class="col-lg-1"></div>
                    <div class="col-lg-5">
                        {!!Form::label('image','Image: ')!!}<br/>
                        @if($new->picturepath == null)
                            <img src="../../images/no-image.jpg" border="4" style="width:240px" />
                        @else
                            <img src="../../images/{{ $new->picturepath }}" style="width:240px" />
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-6">
       {!!Form::submit('Update',['class'=>'btn btn-w-md btn-primary'])!!} <a class="btn btn-w-md btn-danger" href="{!! URL::to('admin') !!}">Cancel</a>
    </div>
</div>
{!! Form::close() !!}
@endsection

resources/views/admin/index.blade.php
@extends('layouts.principal-admin')
@section('content')
<div class="col-md-12">
  <div class="panel panel-filled">
    <div class="panel-heading">
      <h1 class="page-header">All news</h1>
      <div class="row">
        <div class="col-md-12">
          <div class="col-md-6">
            This is all news stored in data base
          </div>
          <div class="col-md-6">
            <a href="{!! URL::to('admin/create') !!}" class="btn btn-w-md btn-accent pull-right">Add new record <i class="fa fa-plus"></i></a>
          </div>
        </div>
      </div><br/>
      @include('alerts.success')
      @include('alerts.error')
    </div>
    <div class="panel-body">
      <div class="table-responsive">
        <table class="table table-hover table-striped">
          <thead>
            <tr>
              <th class="text-center">Id</th>
              <th class="text-center">Tittle</th>
              <th class="text-center">Text</th>
              <th class="text-center">Picture</th>
              <th class="text-center">Action</th>
            </tr>
          </thead>
          @foreach($news as $new)
          <tbody>
            <tr>
              <td>{{ $new->id }}</td>
              <td>{{str_limit($new->title,$limit = 45,$end='...')}}</td>
              <td>{{str_limit($new->text,$limit = 45,$end='...')}}</td>
              @if($new->picturepath == null)
              <td><img src="images/no-image.jpg" alt="" style="width:100px"/></td>
              <td><div class="form-group" align="center"><a href="{!! route('admin.show',$parameters = $new->id) !!}" class="btn btn-success btn-circle" data-tooltip="Ver detalle"><i class="fa fa-search"></i></a>
              <a href="{!! route('admin.edit',$parameters = $new->id) !!}" class="btn btn-primary btn-circle" data-tooltip="Editar new"><i class="glyphicon glyphicon-edit"></i></a>
              <a href="{!! route('admin.destroy',$parameters = $new->id) !!}" class="btn btn-danger btn-circle" data-tooltip="Eliminar new" onclick='return confirm("¿Estas seguro de querer eliminar?")'><i class="glyphicon glyphicon-trash"></i></a></div>
            </td>
            @else
            <td><img src="images/{{$new->picturepath}}" alt="" style="width:100px"/></td>
            <td>
              <div class="form-group" align="center"><a href="{!! route('admin.show',$parameters = $new->id) !!}" class="btn btn-success btn-circle" data-tooltip="Ver detalle"><i class="fa fa-search"></i></a>
              <a href="{!! route('admin.edit',$parameters = $new->id) !!}" class="btn btn-primary btn-circle" data-tooltip="Edit new"><i class="glyphicon glyphicon-edit"></i></a>
              <a href="{!! route('admin.destroy',$parameters = $new->id) !!}" class="btn btn-danger btn-circle" data-tooltip="Eliminar new" onclick='return confirm("¿Estas seguro de querer eliminar?")'><i class="glyphicon glyphicon-trash"></i></a></div>
            </td>
            @endif
          </tr>
        </tbody>
        @endforeach
      </table>
      {!!$news->render()!!}
    </div>
  </div>
</div>
</div>
@endsection

resources/views/admin/show.blade.php
@extends('layouts.principal-admin')
@section('content')
<div class="col-md-12">
    <div class="panel panel-filled">
        <div class="panel-heading">
            <h1 class="page-header">Details</h1>
            Details of new data
        </div>
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-hover table-striped">
                    <thead>
                        <tr>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><h4><b>Title: </b></h4></td>
                            <td><h5>{{ $new->title }}</h5></td>
                        </tr>
                        <tr>
                            <td><h4><b>Text: </b></h4></td>
                            <td><h5>{{ $new->text }}</h5></td>
                        </tr>
                        <tr>
                            <td><h4><b>Created at: </b></h4></td>
                            <td><h5>{{ $new->created_at }}</h5></td>
                        </tr>
                        <tr>
                            <td><h4><b>Modified at: </b></h4></td>
                            <td><h5>{{ $new->updated_at }}</h5></td>
                        </tr>
                        <tr>
                            <td><h4><b>Imagen: </b></h4></td>
                            <td>@if($new->picturepath == null)
                                <img src="../images/no-image.jpg" border="4" style="width:240px" />
                                @else
                                <img src="../images/{{ $new->picturepath }}" style="width:240px" />
                                @endif
                            </td>
                        </tr>
                    </table>
                </div>
                <h1 class="page-header"></h1>
                    <a href="{!! URL::to('admin') !!}" class="btn btn-primary">Go back<i class="fa fa-back"></i></a><br><br><br><br>
            </div>
            
        </div>
    </div>
    @endsection